### ISSUE TITLE
PHP Compatability

### ISSUE THREAD

**Issue by michaelbragg** [vatu-team/workflows#21]
- [ ] Ignore failing tests
- [ ] Var: Path
- [ ] Var: Ignore
- [ ] [Setup-PHP](#0)
- [ ] [PHP Parallel Lint](https://github.com/php-parallel-lint/PHP-Parallel-Lint) - Check all project files.
- [ ] [PHP Compatibility](https://github.com/PHPCompatibility/PHPCompatibility) - 
- [ ] [PHP Stan](https://github.com/phpstan/phpstan) - 

Example: 

```yml
jobs:

  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['8.0', '8.1', '8.2']
        
    steps:
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: mbstring, intl
        ini-values: post_max_size=256M, max_execution_time=180
        coverage: "none"
        tools: parallel-lint, phpcs, phpstan
       env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
    - name: "Install PHP Compatibility."
        run: composer require phpcompatibility/php-compatibility --dev
        
    - name: "Run Parallel Lint
      run: parallel-lint ./   
        
    - name: "Run PHP Compatibility
      run: phpcs -p ./ --standard=./vendor/phpcompatibility/php-compatibility/PHPCompatibility --extensions=php --runtime-set testVersion ${{ matrix.php-versions }}
      
    - name: "Run PHP Stan"
      run: phpstan analyse ./ --level 2
 
```

PHPCS:
```bash
phpcs -p ./public/app/themes/braintumourcharity --standard=./vendor/phpcompatibility/php-compatibility/PHPCompatibility --extensions=php --runtime-set testVersion 8.0-8.2
```

**Comment by michaelbragg** [comment]
Example: https://github.com/vatu-team/demo.vatu.dev/actions/workflows/php-compatibility.yml

Reusable workflow:
```yml
# Vatu: PHP Compatibility
# Version: 0.0.1
# Author: Michael Bragg <mike@vatu.co.uk>
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: "PHP Compatibility"

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}--${{ github.head_ref }}
  cancel-in-progress: true

jobs:

  php-compatibility:

    name: "PHP Compatibility"
    uses: vatu-team/workflows/.github/workflows/php-compatibility.yml@main
    with:
      runs-on: 'self-hosted'
    secrets: inherit
```

Has to be manually called actions tab on the chosen branch.
